### ISSUE TITLE
Consider migrating verification checks from /heartbeat to Telescope?

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#343]
Based on thread here: https://mozilla.slack.com/archives/C022K8JD8QY/p1670881761412369

> i wonder if we're starting to overload heartbeat a bit.  It's basically there for:  "service down, call ops" @mostlygeek 

...perhaps for the jira permissions checks, and, when available, bugzilla webhook checks we can migrate to a telescope instance?

**Comment by leplatrem** [comment]
First, let's try to circle the issue here.

JBI is a system composed of:
- a python app
- a Jira instance
- a Bugzilla instance

The heartbeat should reflect the health of the system. If heartbeat is green, the system is healthy. If heartbeat is red, the system is not healthy.

The key here is therefore to determine what makes JBI healthy or not.

A simple way to approach this would be that the service should be considered unhealthy as soon as consumers are not served. In JBI terms, when Jira issues are not created/updated on Bugzilla events.

This can happen for a number of reasons that we identified:
- The target Jira project has missing permissions
- The configured Jira or Bugzilla credentials are invalid
- The configured Jira components or projects are unknown/invisible
- Bugzilla disables a message queue

These reasons of failure are not related to the application development, but to the application deployment. Operators should be warned as soon as one of these errors is triggered. Operators may have to contact Jira or Bugzilla operators, like they would when something is wrong with any other cloud services. Developers would be put in the loop only once the error happens to be related to the implementation.

Telescope can indeed be put in place, but at a different level, like for example to check consistency between Bugzilla tickets and Jira issues. But I don't think it should be used to check the Bugzilla internals on which JBI relies to sync issues.

**Comment by mostlygeek** [comment]
> The key here is therefore to determine what makes JBI healthy or not.

I would like to expand that to: 

The key here is therefore to determine what makes JBI healthy or not _and_ notify the appropriate operator to repair the system. 

My concern about using only `__heartbeat__` shifts the burden on SRE to be 911 (or 112 in Europe) operators.   I've been told in the past they don't want to be 911/112 operators[1].  From this perspective, I'm hesitant and resistant to accepting a design that creates that system behaviour.  

I would much prefer the `911/112 operator` be automated in code and the appropriate team notified directly.  That may be telescope+pagerduty (my preference) or something else.  

[1] I haven't asked SRE about being 911/112 operators and working on maybe outdated thinking.

**Comment by grahamalama** [comment]
> and notify the appropriate operator to repair the system

Yeah, I wonder if part of the answer here is to remove some of the burden from the heartbeat / SRE by making the system either more self-healing or self-repairable by customers.

For instance, if customers were able to make and manage their own webhooks with Bugzilla, if they noticed their bugs weren't syncing, they'd be able to log into their own Bugzilla account and ensure that the webhook wasn't disabled.

Or, if we were able to more accurately triage Jira errors and determine who or what was responsible, we could email the contact to inform them of the error, if it's something they could fix themselves. Jira issue couldn't be updated because of a workflow rule? The owner of the Jira project may be able to edit the workflow. Jira issue because our credentials are expired, meaning no syncing is happening? Cause for a "911 call".

**Comment by leplatrem** [comment]
I don't think we will ever have a Telescope instance for JBI.

Now that #775 was shipped and deployed, we can rescope this issue into #743
