### ISSUE TITLE
How do we measure the reliablity of JBI? 

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/jira-bugzilla-integration#423]
The flow of information is: `Bugzilla --(a)--> JBI --(b)--> Jira`.  

Questions: 
  * How are we measuring the reliability of `a` and `b`? 
  * What is the troubleshooting process when we discover issues `a` or `b`?

**Comment by bsieber-mozilla** [comment]
In terms of "measuring the reliability" I believe...
(a) was partially addressed in #395--which I believe has yet to be rolled out to prod.
(b) is mainly addressed in the healthcheck--where we confirm permissions for projects listed in the configuration.

There is currently an issue in which our service account is unable to update Jira, because the issue was moved to a restricted state/permission outside of JBI's scope (#415).

**Comment by mostlygeek** [comment]
From the meeting today: 

1. Sentry data to measure exceptions
2. For exceptions that happen frequently (tbd) we will explore adding edge case handling into JBI code 
3. For exceptions that happen infrequently (tbd) we will ignore them unless they cause customer complaints 
4. We will review sentry exception/error data periodically - at our weekly meeting, or bi-weekly
