### ISSUE TITLE
Errors occur when linked Jira issue does not match project in config

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#635]
https://mozilla.sentry.io/issues/4320816876/?referrer=slack&alert_rule_id=11827252&alert_type=issue

**Steps to reproduce**

1. configure tag `[foo]` to be associated with project `FOO`
2. `bug 9999` receives tag `[foo]`
3. Jira issue `FOO-123` gets created
4. `bug 9999` receives link to `FOO-123` 
5. configuration is changed to associate `[foo]` with project `BAR`
6. `bug 9999` receives a change (eg. status)
7. actions associated to `[foo]` are executed with project `BAR` in context
8.  actions like `maybe_update_components` will inspect the `BAR` project, and will try to apply the changes on the `FOO-123` issue which is in the `FOO` project.

**Solution Ideas**

* Abort workflow when linked issue does not match project in config
* Put the project from the linked issue as context instead of the one in config

The former makes more sense, because for other actions like `maybe_update_status` where a mapping is defined in configuration, using the linked issue's project can be confusing since it may not have the same mappings...

**Comment by grahamalama** [comment]
In #636, the approach is to ignore the case where the linked Jira issue on a bug doesn't match the project that the whiteboard tag is configured with. e.g

- `bug 9999` has a Jira link pointing to a project `FOO`
- the whiteboard tag on the bug is configured to be associated with project `BAR`
- since there is a mismatch, we ignore the bug update 

Should we instead (or maybe follow up after #636 is landed) "move" the Jira issue? Since there is a mismatch, we delete the issue from project `FOO` and recreate it in project `BAR`. Unfortunately, it doesn't look like there's an API endpoint to do this. It's currently [under consideration](https://jira.atlassian.com/browse/JRACLOUD-70305) by the JIRA team.

This might be something to ask customers about.

**Comment by leplatrem** [comment]
> Did this actually happen? This is what setup the eventual Sentry issue?

Since customer said that `FNXV2` was the legacy Jira project for `FXDROID`, I thought it did.

But it wasn't exactly this, it's just that a user added manually both the tag and the link to Jira on the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1794872#a13307585_430528

We don't do anything to prevent any of the two possible scenarios, so it must be handled.

> Should we instead (or maybe follow up after https://github.com/mozilla/jira-bugzilla-integration/pull/636 is landed) "move" the Jira issue?

If there was an easy way, why not, but so far ignoring seems to be the safest.

> Since there is a mismatch, we delete the issue from project FOO and recreate it in project BAR. 

But we would potentially loose history, or extra stuff like comments, attachments, etc. 

> This might be something to ask customers about.

[Customer said](https://mozilla.slack.com/archives/C016BTJKM9B/p1690208863555469?thread_ts=1689595321.417929&cid=C016BTJKM9B) "we don’t really even need to worry about an error, here, if it’d be possible for us to turn them off)" [...] "simply allowing this kind of component sync failure to happen, if the Jira ticket finds itself in a project that doesn’t contain a matching component)"
